### PR TITLE
Add offline usage examples (Node.js)

### PR DESCRIPTION
**Pull request by adam-of-barot**
Adding examples focusing on offline/server-side usage using Node.js (see #160).

The examples try to mirror the vanilla javascript examples in `examples/javascript`

To run an example file, run the following command:
`node <path of the example file>`

### CODE REVIEW

**Comment by MichelML** [comment]
sorry for the delay here @adam-of-barot , I'll get to it real soon, my newborn is 2 months old now but I'm still trying to figure out my schedule and workflow :baby:

**Comment by adam-of-barot** [comment]
Hey @MichelML, no problems.
If all goes well, I'll soon find out in a few months what it's like to have a newborn as well.

Best of luck, and a belated Happy New Years!

**Comment by MichelML** [comment]
Congrats @adam-of-barot !!!

**Comment by MichelML** [comment]
@adam-of-barot this is great! I can't seem to make edits of your PR some how, I will merge and make further edits in master, thanks for this!

**Pull request merged**
