### PR TITLE
Update type definitions

### PR DESCRIPTION
**Pull request by adam-of-barot**
Updated the following function signature definitions to reflect the changes made in the Q1 2023 update.
- get_morgan_fp()
- get_morgan_fp_as_uint8array()
- get_pattern_fp()
- get_pattern_fp_as_uint8array()

### CODE REVIEW

**Review by MichelML — APPROVED** [review]
Thanks for this @adam-of-barot

**Comment by MichelML** [comment]
@adam-of-barot did you test if related examples were still working?

**Comment by adam-of-barot** [comment]
Currently I found no examples using these functions.
The only things I found was a call to `get_morgan_fp()` in `docs/demo.html`.

**Comment by MichelML** [comment]
perfect @adam-of-barot , merging now :pray: , thank you!

**Pull request merged**
