### PR TITLE
Add Vue examples

### PR DESCRIPTION
**Pull request by adam-of-barot**
#2 
Added Vue examples mimicking the React examples.
The project was scaffolded with Typescript support, so this can also be used as an example on how to implement the new type definitions.

Features missing:

- ~~syntax highlighting for code examples~~ (added)

- ~~accordion to hide code examples~~ (added)

### CODE REVIEW

**Comment by MichelML** [comment]
@adam-of-barot thanks for this, I'll try to review this by the end of the week :+1:

**Comment by MichelML** [comment]
@adam-of-barot , wow! these examples are great! I'm impressed by how close you got to the styling of the other examples in react and javascript. And, that no examples are missing and they are all working great.

I just finalized the PR with this commit https://github.com/rdkit/rdkit-js/pull/169/commits/6f2cd3239cb156251c787a1e18d5a98a07a3bb5e  

The website vue.rdkitjs.com should be deployed post merge of this PR , thanks a lot for this!

**Review by MichelML — APPROVED** [review]

**Comment by MichelML** [comment]
@adam-of-barot I'm currently having issues running `npm run vue:build` from the root of the repo. I get a lot of typescript compiling errors. Same when I run `npm run build` from the root of the examples/vue repo.

Can you fix this before we merge this PR? Otherwise, we won't be able to deploy the vue.rdkitjs.com website

**Review by MichelML — CHANGES_REQUESTED** [review]
`npm run vue:build` must pass before merging

**Comment by adam-of-barot** [comment]
@MichelML Thank you for the review and the mentions in the docs!
After a bit of searching it seems that I only had to change 1 thing in the `tsconfig.json` for most of the errors to go away, and add a `delete()` method to `index.d.ts`.

I've successfully ran both `npm run build` from inside the /examples/vue repo, and `npm run vue:build` from the project root.
Hopefully it works for you too.

**Review by MichelML — APPROVED** [review]

**Comment by MichelML** [comment]
works like a charm @adam-of-barot ! Let's merge this :+1:

**Comment by MichelML** [comment]
up and running @adam-of-barot https://vue.rdkitjs.com/

**Pull request merged**
